import { Domain } from "../types.js";
import type { CatalogEntry } from "../types.js";

export const pipelineEntries: CatalogEntry[] = [
  { id: "pipelines.listDefinitions", domain: Domain.Pipelines, name: "listDefinitions", title: "List Pipeline Definitions", description: "List all pipeline/build definitions in a project.", params: [{ name: "project", type: "string", required: true, description: "Project name" }, { name: "name", type: "string", required: false, description: "Filter by name" }], returns: "PipelineDefinition[] — definitions with id, name, path", example: 'await ado.pipelines.listDefinitions({ project: "MyProj" })', tags: ["pipeline", "definition", "list", "ci", "cd", "build"], readOnly: true },
  { id: "pipelines.getDefinition", domain: Domain.Pipelines, name: "getDefinition", title: "Get Pipeline Definition", description: "Get a pipeline definition by ID.", params: [{ name: "project", type: "string", required: true, description: "Project name" }, { name: "definitionId", type: "number", required: true, description: "Definition ID" }], returns: "PipelineDefinition — full definition details", example: 'await ado.pipelines.getDefinition({ project: "MyProj", definitionId: 42 })', tags: ["pipeline", "definition", "details", "config"], readOnly: true },
  { id: "pipelines.listBuilds", domain: Domain.Pipelines, name: "listBuilds", title: "List Builds", description: "List recent builds, optionally filtered by definition or status.", params: [{ name: "project", type: "string", required: true, description: "Project name" }, { name: "definitionId", type: "number", required: false, description: "Filter by pipeline definition" }, { name: "status", type: "string", required: false, description: "completed, inProgress, cancelling, notStarted" }, { name: "top", type: "number", required: false, description: "Max results" }], returns: "Build[] — builds with id, number, status, result", example: 'await ado.pipelines.listBuilds({ project: "MyProj", top: 10 })', tags: ["build", "pipeline", "list", "recent", "runs", "history"], readOnly: true },
  { id: "pipelines.getBuild", domain: Domain.Pipelines, name: "getBuild", title: "Get Build", description: "Get details of a specific build run.", params: [{ name: "project", type: "string", required: true, description: "Project name" }, { name: "buildId", type: "number", required: true, description: "Build ID" }], returns: "Build — full build details with status, result, timeline", example: 'await ado.pipelines.getBuild({ project: "MyProj", buildId: 999 })', tags: ["build", "pipeline", "details", "status", "result", "run"], readOnly: true },
  { id: "pipelines.getBuildLog", domain: Domain.Pipelines, name: "getBuildLog", title: "Get Build Log", description: "Get logs for a build. Use logId for a specific task log.", params: [{ name: "project", type: "string", required: true, description: "Project name" }, { name: "buildId", type: "number", required: true, description: "Build ID" }, { name: "logId", type: "number", required: false, description: "Specific log ID (from timeline)" }], returns: "string — log content", example: 'await ado.pipelines.getBuildLog({ project: "MyProj", buildId: 999 })', tags: ["build", "log", "output", "console", "errors", "debug"], readOnly: true },
  { id: "pipelines.getBuildTimeline", domain: Domain.Pipelines, name: "getBuildTimeline", title: "Get Build Timeline", description: "Get the timeline of stages, jobs, and tasks for a build.", params: [{ name: "project", type: "string", required: true, description: "Project name" }, { name: "buildId", type: "number", required: true, description: "Build ID" }], returns: "Timeline — stages, jobs, tasks with status and duration", example: 'await ado.pipelines.getBuildTimeline({ project: "MyProj", buildId: 999 })', tags: ["build", "timeline", "stages", "jobs", "tasks", "progress"], readOnly: true },
  { id: "pipelines.runPipeline", domain: Domain.Pipelines, name: "runPipeline", title: "Run Pipeline", description: "Trigger a new pipeline build run.", params: [{ name: "project", type: "string", required: true, description: "Project name" }, { name: "definitionId", type: "number", required: true, description: "Pipeline definition ID" }, { name: "branch", type: "string", required: false, description: "Source branch (default: default branch)" }, { name: "parameters", type: "object", required: false, description: "Pipeline parameters" }], returns: "Build — the queued build", example: 'await ado.pipelines.runPipeline({ project: "MyProj", definitionId: 42, branch: "main" })', tags: ["pipeline", "run", "trigger", "build", "start", "deploy", "ci", "cd"], readOnly: false },
  { id: "pipelines.cancelBuild", domain: Domain.Pipelines, name: "cancelBuild", title: "Cancel Build", description: "Cancel a running build.", params: [{ name: "project", type: "string", required: true, description: "Project name" }, { name: "buildId", type: "number", required: true, description: "Build ID" }], returns: "Build — the cancelled build", example: 'await ado.pipelines.cancelBuild({ project: "MyProj", buildId: 999 })', tags: ["build", "cancel", "stop", "abort"], readOnly: false },
  { id: "pipelines.listReleases", domain: Domain.Pipelines, name: "listReleases", title: "List Releases", description: "List releases (classic release pipelines).", params: [{ name: "project", type: "string", required: true, description: "Project name" }, { name: "definitionId", type: "number", required: false, description: "Release definition ID" }, { name: "top", type: "number", required: false, description: "Max results" }], returns: "Release[] — releases with id, name, status, environments", example: 'await ado.pipelines.listReleases({ project: "MyProj" })', tags: ["release", "deploy", "deployment", "environment", "classic"], readOnly: true },
  { id: "pipelines.getRelease", domain: Domain.Pipelines, name: "getRelease", title: "Get Release", description: "Get details of a specific release.", params: [{ name: "project", type: "string", required: true, description: "Project name" }, { name: "releaseId", type: "number", required: true, description: "Release ID" }], returns: "Release — full release with environment statuses", example: 'await ado.pipelines.getRelease({ project: "MyProj", releaseId: 55 })', tags: ["release", "deploy", "details", "environment", "status"], readOnly: true },
  { id: "pipelines.listArtifacts", domain: Domain.Pipelines, name: "listArtifacts", title: "List Build Artifacts", description: "List artifacts produced by a build.", params: [{ name: "project", type: "string", required: true, description: "Project name" }, { name: "buildId", type: "number", required: true, description: "Build ID" }], returns: "Artifact[] — build artifacts with name, type, resource", example: 'await ado.pipelines.listArtifacts({ project: "MyProj", buildId: 999 })', tags: ["artifact", "build", "output", "package", "drop"], readOnly: true },
  { id: "pipelines.getBuildChanges", domain: Domain.Pipelines, name: "getBuildChanges", title: "Get Build Changes", description: "Get the source changes (commits) associated with a build.", params: [{ name: "project", type: "string", required: true, description: "Project name" }, { name: "buildId", type: "number", required: true, description: "Build ID" }], returns: "Change[] — commits included in the build", example: 'await ado.pipelines.getBuildChanges({ project: "MyProj", buildId: 999 })', tags: ["build", "changes", "commits", "what changed", "changelog"], readOnly: true },
];
