import { Domain } from "../types.js";
import type { CatalogEntry } from "../types.js";

export const repositoryEntries: CatalogEntry[] = [
  { id: "repositories.listRepos", domain: Domain.Repositories, name: "listRepos", title: "List Repositories", description: "List all git repositories in a project.", params: [{ name: "project", type: "string", required: true, description: "Project name" }], returns: "Repo[] — repositories with id, name, defaultBranch", example: 'await ado.repos.list({ project: "MyProj" })', tags: ["repo", "repository", "git", "list", "all"], readOnly: true },
  { id: "repositories.getRepo", domain: Domain.Repositories, name: "getRepo", title: "Get Repository", description: "Get a repository by name or ID.", params: [{ name: "nameOrId", type: "string", required: true, description: "Repository name or GUID" }], returns: "Repo — repository details", example: 'await ado.repos.get("my-repo")', tags: ["repo", "repository", "git", "details"], readOnly: true },
  { id: "repositories.listPullRequests", domain: Domain.Repositories, name: "listPullRequests", title: "List Pull Requests", description: "List pull requests, optionally filtered by repo and status.", params: [{ name: "project", type: "string", required: true, description: "Project name" }, { name: "repoId", type: "string", required: false, description: "Repository ID to filter" }, { name: "status", type: "string", required: false, description: "active, completed, abandoned, or all" }, { name: "top", type: "number", required: false, description: "Max results" }], returns: "PR[] — pull requests with id, title, status, branches", example: 'await ado.repos.listPullRequests({ project: "MyProj", status: "active" })', tags: ["pr", "pull request", "review", "merge", "list"], readOnly: true },
  { id: "repositories.getPullRequest", domain: Domain.Repositories, name: "getPullRequest", title: "Get Pull Request", description: "Get a pull request by ID.", params: [{ name: "id", type: "number", required: true, description: "Pull request ID" }], returns: "PR — full pull request details", example: "await ado.repos.getPullRequest(12345)", tags: ["pr", "pull request", "details", "review"], readOnly: true },
  { id: "repositories.createPullRequest", domain: Domain.Repositories, name: "createPullRequest", title: "Create Pull Request", description: "Create a new pull request.", params: [{ name: "repoId", type: "string", required: true, description: "Repository ID" }, { name: "title", type: "string", required: true, description: "PR title" }, { name: "source", type: "string", required: true, description: "Source branch" }, { name: "target", type: "string", required: false, description: "Target branch (default: main)" }, { name: "description", type: "string", required: false, description: "PR description" }], returns: "PR — the created pull request", example: 'await ado.repos.createPullRequest({ repoId: "abc", title: "Add feature", source: "feature/x" })', tags: ["pr", "pull request", "create", "new", "merge request"], readOnly: false },
  { id: "repositories.updatePullRequest", domain: Domain.Repositories, name: "updatePullRequest", title: "Update Pull Request", description: "Update PR properties (title, description, status, auto-complete).", params: [{ name: "repoId", type: "string", required: true, description: "Repository ID" }, { name: "pullRequestId", type: "number", required: true, description: "PR ID" }, { name: "updates", type: "object", required: true, description: "Fields to update" }], returns: "PR — updated pull request", example: 'await ado.repos.updatePullRequest({ repoId: "abc", pullRequestId: 123, updates: { status: "completed" } })', tags: ["pr", "pull request", "update", "complete", "abandon", "merge"], readOnly: false },
  { id: "repositories.listBranches", domain: Domain.Repositories, name: "listBranches", title: "List Branches", description: "List branches in a repository.", params: [{ name: "repoId", type: "string", required: true, description: "Repository ID" }], returns: "Branch[] — branches with name, commit, ahead/behind", example: 'await ado.repos.listBranches("my-repo-id")', tags: ["branch", "branches", "git", "ref"], readOnly: true },
  { id: "repositories.getFileContent", domain: Domain.Repositories, name: "getFileContent", title: "Get File Content", description: "Get contents of a file from a repository.", params: [{ name: "repoId", type: "string", required: true, description: "Repository ID" }, { name: "path", type: "string", required: true, description: "File path" }, { name: "branch", type: "string", required: false, description: "Branch name" }], returns: "string — file content", example: 'await ado.repos.getFileContent({ repoId: "abc", path: "/src/main.ts", branch: "main" })', tags: ["file", "content", "read", "source", "code"], readOnly: true },
  { id: "repositories.listCommits", domain: Domain.Repositories, name: "listCommits", title: "List Commits", description: "List commits in a repository.", params: [{ name: "repoId", type: "string", required: true, description: "Repository ID" }, { name: "branch", type: "string", required: false, description: "Branch name" }, { name: "top", type: "number", required: false, description: "Max results" }], returns: "Commit[] — commits with id, message, author, date", example: 'await ado.repos.listCommits({ repoId: "abc", branch: "main", top: 20 })', tags: ["commit", "history", "log", "git", "changes"], readOnly: true },
  { id: "repositories.getCommit", domain: Domain.Repositories, name: "getCommit", title: "Get Commit", description: "Get details of a specific commit.", params: [{ name: "repoId", type: "string", required: true, description: "Repository ID" }, { name: "commitId", type: "string", required: true, description: "Commit SHA" }], returns: "Commit — full commit details with changes", example: 'await ado.repos.getCommit({ repoId: "abc", commitId: "abc123" })', tags: ["commit", "details", "diff", "sha"], readOnly: true },
  { id: "repositories.getDiff", domain: Domain.Repositories, name: "getDiff", title: "Get Diff", description: "Get diff between two commits or branches.", params: [{ name: "repoId", type: "string", required: true, description: "Repository ID" }, { name: "base", type: "string", required: true, description: "Base commit/branch" }, { name: "target", type: "string", required: true, description: "Target commit/branch" }], returns: "Diff — list of changed files with content", example: 'await ado.repos.getDiff({ repoId: "abc", base: "main", target: "feature/x" })', tags: ["diff", "compare", "changes", "delta", "merge base"], readOnly: true },
  { id: "repositories.getPullRequestThreads", domain: Domain.Repositories, name: "getPullRequestThreads", title: "Get PR Threads", description: "Get review threads/comments on a pull request.", params: [{ name: "repoId", type: "string", required: true, description: "Repository ID" }, { name: "pullRequestId", type: "number", required: true, description: "PR ID" }], returns: "Thread[] — review threads with comments", example: 'await ado.repos.getPullRequestThreads({ repoId: "abc", pullRequestId: 123 })', tags: ["pr", "pull request", "threads", "comments", "review", "feedback"], readOnly: true },
  { id: "repositories.createPullRequestThread", domain: Domain.Repositories, name: "createPullRequestThread", title: "Comment on Pull Request", description: "Create a new review thread/comment on a pull request.", params: [{ name: "repoId", type: "string", required: true, description: "Repository ID" }, { name: "pullRequestId", type: "number", required: true, description: "PR ID" }, { name: "comment", type: "string", required: true, description: "Comment text" }, { name: "filePath", type: "string", required: false, description: "File path for inline comment" }, { name: "line", type: "number", required: false, description: "Line number for inline comment" }], returns: "Thread — the created thread", example: 'await ado.repos.createPullRequestThread({ repoId: "abc", pullRequestId: 123, comment: "LGTM" })', tags: ["pr", "pull request", "comment", "review", "feedback", "thread"], readOnly: false },
  { id: "repositories.addPullRequestReviewer", domain: Domain.Repositories, name: "addPullRequestReviewer", title: "Add PR Reviewer", description: "Add a reviewer to a pull request.", params: [{ name: "repoId", type: "string", required: true, description: "Repository ID" }, { name: "pullRequestId", type: "number", required: true, description: "PR ID" }, { name: "reviewerId", type: "string", required: true, description: "Reviewer identity ID" }], returns: "void", example: 'await ado.repos.addPullRequestReviewer({ repoId: "abc", pullRequestId: 123, reviewerId: "user-guid" })', tags: ["pr", "pull request", "reviewer", "assign", "approval"], readOnly: false },
  { id: "repositories.listPullRequestWorkItems", domain: Domain.Repositories, name: "listPullRequestWorkItems", title: "List PR Work Items", description: "List work items linked to a pull request.", params: [{ name: "repoId", type: "string", required: true, description: "Repository ID" }, { name: "pullRequestId", type: "number", required: true, description: "PR ID" }], returns: "WorkItemRef[] — linked work items", example: 'await ado.repos.listPullRequestWorkItems({ repoId: "abc", pullRequestId: 123 })', tags: ["pr", "pull request", "work items", "linked", "related"], readOnly: true },
  { id: "repositories.listItems", domain: Domain.Repositories, name: "listItems", title: "List Repository Items (Tree)", description: "List files and folders in a repository path.", params: [{ name: "repoId", type: "string", required: true, description: "Repository ID" }, { name: "path", type: "string", required: false, description: "Path (default: root)" }, { name: "branch", type: "string", required: false, description: "Branch name" }], returns: "TreeEntry[] — files and folders", example: 'await ado.repos.listItems({ repoId: "abc", path: "/src" })', tags: ["file", "folder", "tree", "directory", "browse", "ls"], readOnly: true },
  { id: "repositories.createBranch", domain: Domain.Repositories, name: "createBranch", title: "Create Branch", description: "Create a new branch from a source ref.", params: [{ name: "repoId", type: "string", required: true, description: "Repository ID" }, { name: "name", type: "string", required: true, description: "New branch name" }, { name: "sourceRef", type: "string", required: true, description: "Source commit or branch" }], returns: "Branch — the created branch", example: 'await ado.repos.createBranch({ repoId: "abc", name: "feature/new", sourceRef: "main" })', tags: ["branch", "create", "new", "git"], readOnly: false },
  { id: "repositories.deleteBranch", domain: Domain.Repositories, name: "deleteBranch", title: "Delete Branch", description: "Delete a branch.", params: [{ name: "repoId", type: "string", required: true, description: "Repository ID" }, { name: "name", type: "string", required: true, description: "Branch name" }], returns: "void", example: 'await ado.repos.deleteBranch({ repoId: "abc", name: "feature/old" })', tags: ["branch", "delete", "remove", "cleanup"], readOnly: false },
  { id: "repositories.getStats", domain: Domain.Repositories, name: "getStats", title: "Get Repository Stats", description: "Get branch statistics (ahead/behind counts).", params: [{ name: "repoId", type: "string", required: true, description: "Repository ID" }, { name: "branch", type: "string", required: false, description: "Branch name" }], returns: "BranchStats — ahead/behind counts relative to default branch", example: 'await ado.repos.getStats({ repoId: "abc", branch: "feature/x" })', tags: ["stats", "statistics", "ahead", "behind", "branch", "compare"], readOnly: true },
];
