import { Domain } from "../types.js";
import type { CatalogEntry } from "../types.js";

export const testPlanEntries: CatalogEntry[] = [
  { id: "test-plans.listTestPlans", domain: Domain.TestPlans, name: "listTestPlans", title: "List Test Plans", description: "List test plans in a project.", params: [{ name: "project", type: "string", required: true, description: "Project name" }], returns: "TestPlan[] — plans with id, name, state", example: 'await ado.testPlans.listPlans({ project: "MyProj" })', tags: ["test", "plan", "list", "qa", "quality"], readOnly: true },
  { id: "test-plans.getTestPlan", domain: Domain.TestPlans, name: "getTestPlan", title: "Get Test Plan", description: "Get details of a specific test plan.", params: [{ name: "project", type: "string", required: true, description: "Project name" }, { name: "planId", type: "number", required: true, description: "Test plan ID" }], returns: "TestPlan — full plan with suites and configuration", example: 'await ado.testPlans.getPlan({ project: "MyProj", planId: 1 })', tags: ["test", "plan", "details", "qa"], readOnly: true },
  { id: "test-plans.listTestSuites", domain: Domain.TestPlans, name: "listTestSuites", title: "List Test Suites", description: "List test suites in a test plan.", params: [{ name: "project", type: "string", required: true, description: "Project name" }, { name: "planId", type: "number", required: true, description: "Test plan ID" }], returns: "TestSuite[] — suites with id, name, type", example: 'await ado.testPlans.listSuites({ project: "MyProj", planId: 1 })', tags: ["test", "suite", "list", "qa", "organize"], readOnly: true },
  { id: "test-plans.listTestCases", domain: Domain.TestPlans, name: "listTestCases", title: "List Test Cases", description: "List test cases in a test suite.", params: [{ name: "project", type: "string", required: true, description: "Project name" }, { name: "planId", type: "number", required: true, description: "Test plan ID" }, { name: "suiteId", type: "number", required: true, description: "Test suite ID" }], returns: "TestCase[] — test cases with steps and expected results", example: 'await ado.testPlans.listCases({ project: "MyProj", planId: 1, suiteId: 2 })', tags: ["test", "case", "list", "qa", "steps"], readOnly: true },
  { id: "test-plans.createTestCase", domain: Domain.TestPlans, name: "createTestCase", title: "Create Test Case", description: "Create a new test case.", params: [{ name: "project", type: "string", required: true, description: "Project name" }, { name: "planId", type: "number", required: true, description: "Test plan ID" }, { name: "suiteId", type: "number", required: true, description: "Test suite ID" }, { name: "title", type: "string", required: true, description: "Test case title" }], returns: "TestCase — the created test case", example: 'await ado.testPlans.createCase({ project: "MyProj", planId: 1, suiteId: 2, title: "Verify login flow" })', tags: ["test", "case", "create", "new", "qa"], readOnly: false },
  { id: "test-plans.getTestResults", domain: Domain.TestPlans, name: "getTestResults", title: "Get Test Results", description: "Get test results from a build or release.", params: [{ name: "project", type: "string", required: true, description: "Project name" }, { name: "buildId", type: "number", required: true, description: "Build ID" }], returns: "TestResult[] — results with outcome, duration, error message", example: 'await ado.testPlans.getResults({ project: "MyProj", buildId: 999 })', tags: ["test", "results", "pass", "fail", "build", "qa", "outcome"], readOnly: true },
  { id: "test-plans.getTestRunById", domain: Domain.TestPlans, name: "getTestRunById", title: "Get Test Run", description: "Get details of a specific test run.", params: [{ name: "project", type: "string", required: true, description: "Project name" }, { name: "runId", type: "number", required: true, description: "Test run ID" }], returns: "TestRun — run details with statistics", example: 'await ado.testPlans.getRun({ project: "MyProj", runId: 42 })', tags: ["test", "run", "details", "execution", "qa"], readOnly: true },
  { id: "test-plans.createTestRun", domain: Domain.TestPlans, name: "createTestRun", title: "Create Test Run", description: "Create a new test run.", params: [{ name: "project", type: "string", required: true, description: "Project name" }, { name: "planId", type: "number", required: true, description: "Test plan ID" }, { name: "name", type: "string", required: true, description: "Run name" }], returns: "TestRun — the created test run", example: 'await ado.testPlans.createRun({ project: "MyProj", planId: 1, name: "Regression run" })', tags: ["test", "run", "create", "execute", "qa"], readOnly: false },
];
