import { Domain } from "../types.js";
import type { CatalogEntry } from "../types.js";

export const wikiEntries: CatalogEntry[] = [
  { id: "wiki.listWikis", domain: Domain.Wiki, name: "listWikis", title: "List Wikis", description: "List all wikis in a project.", params: [{ name: "project", type: "string", required: true, description: "Project name" }], returns: "Wiki[] — wikis with id, name, type", example: 'await ado.wiki.list("MyProj")', tags: ["wiki", "list", "documentation", "knowledge base"], readOnly: true },
  { id: "wiki.getPage", domain: Domain.Wiki, name: "getPage", title: "Get Wiki Page", description: "Get content of a wiki page.", params: [{ name: "project", type: "string", required: true, description: "Project name" }, { name: "wikiId", type: "string", required: true, description: "Wiki name or ID" }, { name: "path", type: "string", required: true, description: "Page path (e.g. /Home)" }], returns: "WikiPage — page content and metadata", example: 'await ado.wiki.getPage({ project: "MyProj", wikiId: "MyWiki", path: "/Home" })', tags: ["wiki", "page", "content", "read", "documentation"], readOnly: true },
  { id: "wiki.listPages", domain: Domain.Wiki, name: "listPages", title: "List Wiki Pages", description: "List pages in a wiki.", params: [{ name: "project", type: "string", required: true, description: "Project name" }, { name: "wikiId", type: "string", required: true, description: "Wiki name or ID" }, { name: "path", type: "string", required: false, description: "Root path to list from" }], returns: "WikiPage[] — pages with path and order", example: 'await ado.wiki.listPages({ project: "MyProj", wikiId: "MyWiki" })', tags: ["wiki", "pages", "list", "table of contents", "browse"], readOnly: true },
  { id: "wiki.createOrUpdatePage", domain: Domain.Wiki, name: "createOrUpdatePage", title: "Create or Update Wiki Page", description: "Create or update a wiki page with markdown content.", params: [{ name: "project", type: "string", required: true, description: "Project name" }, { name: "wikiId", type: "string", required: true, description: "Wiki name or ID" }, { name: "path", type: "string", required: true, description: "Page path" }, { name: "content", type: "string", required: true, description: "Markdown content" }], returns: "WikiPage — the created/updated page", example: 'await ado.wiki.createOrUpdatePage({ project: "MyProj", wikiId: "MyWiki", path: "/New Page", content: "# Hello" })', tags: ["wiki", "page", "create", "update", "write", "edit", "markdown"], readOnly: false },
  { id: "wiki.deletePage", domain: Domain.Wiki, name: "deletePage", title: "Delete Wiki Page", description: "Delete a wiki page.", params: [{ name: "project", type: "string", required: true, description: "Project name" }, { name: "wikiId", type: "string", required: true, description: "Wiki name or ID" }, { name: "path", type: "string", required: true, description: "Page path" }], returns: "void", example: 'await ado.wiki.deletePage({ project: "MyProj", wikiId: "MyWiki", path: "/Old Page" })', tags: ["wiki", "page", "delete", "remove"], readOnly: false },
];
