import { Domain } from "../types.js";
import type { CatalogEntry } from "../types.js";

export const workEntries: CatalogEntry[] = [
  { id: "work.listTeamIterations", domain: Domain.Work, name: "listTeamIterations", title: "List Team Iterations", description: "List iterations (sprints) for a team. Use timeframe='current' for active sprint.", params: [{ name: "project", type: "string", required: true, description: "Project name" }, { name: "team", type: "string", required: true, description: "Team name" }, { name: "timeframe", type: "string", required: false, description: "'current' for active sprint" }], returns: "Iteration[] — list with id, name, path, start/end dates", example: 'await ado.work.listTeamIterations({ project: "MyProj", team: "MyTeam", timeframe: "current" })', tags: ["sprint", "iteration", "current sprint", "team", "dates", "schedule"], readOnly: true },
  { id: "work.getWorkItemsForIteration", domain: Domain.Work, name: "getWorkItemsForIteration", title: "Get Work Items For Iteration", description: "Get work item IDs assigned to a specific sprint/iteration.", params: [{ name: "project", type: "string", required: true, description: "Project name" }, { name: "team", type: "string", required: true, description: "Team name" }, { name: "iterationId", type: "string", required: true, description: "Iteration ID" }], returns: "WorkItemRef[] — work item references with IDs", example: 'await ado.work.getWorkItemsForIteration({ project: "MyProj", team: "MyTeam", iterationId: "abc-123" })', tags: ["sprint", "iteration", "work items", "sprint items", "assigned"], readOnly: true },
  { id: "work.getTeamCapacity", domain: Domain.Work, name: "getTeamCapacity", title: "Get Team Capacity", description: "Get capacity for team members in an iteration.", params: [{ name: "project", type: "string", required: true, description: "Project name" }, { name: "team", type: "string", required: true, description: "Team name" }, { name: "iterationId", type: "string", required: true, description: "Iteration ID" }], returns: "Capacity — team member capacities and totals", example: 'await ado.work.getTeamCapacity({ project: "MyProj", team: "MyTeam", iterationId: "abc" })', tags: ["capacity", "team", "sprint", "hours", "availability"], readOnly: true },
  { id: "work.getTeamSettings", domain: Domain.Work, name: "getTeamSettings", title: "Get Team Settings", description: "Get team settings including backlog and iteration paths.", params: [{ name: "project", type: "string", required: true, description: "Project name" }, { name: "team", type: "string", required: true, description: "Team name" }], returns: "TeamSettings — backlog, iteration, and working day settings", example: 'await ado.work.getTeamSettings({ project: "MyProj", team: "MyTeam" })', tags: ["team", "settings", "configuration", "backlog", "iteration path"], readOnly: true },
  { id: "work.getTeamFieldValues", domain: Domain.Work, name: "getTeamFieldValues", title: "Get Team Field Values", description: "Get field values for the team (area path, iteration path).", params: [{ name: "project", type: "string", required: true, description: "Project name" }, { name: "team", type: "string", required: true, description: "Team name" }], returns: "TeamFieldValues — default and allowed values", example: 'await ado.work.getTeamFieldValues({ project: "MyProj", team: "MyTeam" })', tags: ["team", "fields", "area path", "iteration path", "defaults"], readOnly: true },
  { id: "work.getTeamDaysOff", domain: Domain.Work, name: "getTeamDaysOff", title: "Get Team Days Off", description: "Get days off for team in an iteration.", params: [{ name: "project", type: "string", required: true, description: "Project name" }, { name: "team", type: "string", required: true, description: "Team name" }, { name: "iterationId", type: "string", required: true, description: "Iteration ID" }], returns: "TeamDaysOff — date ranges of days off", example: 'await ado.work.getTeamDaysOff({ project: "MyProj", team: "MyTeam", iterationId: "abc" })', tags: ["team", "days off", "vacation", "holiday", "sprint"], readOnly: true },
  { id: "work.getBoard", domain: Domain.Work, name: "getBoard", title: "Get Board", description: "Get a team's board configuration.", params: [{ name: "project", type: "string", required: true, description: "Project name" }, { name: "team", type: "string", required: true, description: "Team name" }, { name: "boardId", type: "string", required: true, description: "Board name or ID" }], returns: "Board — board configuration with columns and rows", example: 'await ado.work.getBoard({ project: "MyProj", team: "MyTeam", boardId: "Stories" })', tags: ["board", "kanban", "columns", "swimlanes", "agile"], readOnly: true },
  { id: "work.getBoardColumns", domain: Domain.Work, name: "getBoardColumns", title: "Get Board Columns", description: "Get columns for a team board.", params: [{ name: "project", type: "string", required: true, description: "Project name" }, { name: "team", type: "string", required: true, description: "Team name" }, { name: "boardId", type: "string", required: true, description: "Board name or ID" }], returns: "BoardColumn[] — list of columns with names, limits, and state mappings", example: 'await ado.work.getBoardColumns({ project: "MyProj", team: "MyTeam", boardId: "Stories" })', tags: ["board", "columns", "kanban", "WIP limit", "workflow"], readOnly: true },
];
