import { Domain } from "../types.js";
import type { CatalogEntry } from "../types.js";

export const workItemEntries: CatalogEntry[] = [
  {
    id: "work-items.get", domain: Domain.WorkItems, name: "get",
    title: "Get Work Item", description: "Fetch a single work item by ID with all fields.",
    params: [
      { name: "id", type: "number", required: true, description: "Work item ID" },
      { name: "fields", type: "string[]", required: false, description: "Specific fields to return" },
      { name: "expand", type: "boolean", required: false, description: "Expand relations" },
    ],
    returns: "WorkItem — full work item with fields, relations, and metadata",
    example: "await ado.workItems.get(12345)", tags: ["work item", "bug", "story", "task", "pbi", "fetch", "read", "get"], readOnly: true,
  },
  {
    id: "work-items.getBatch", domain: Domain.WorkItems, name: "getBatch",
    title: "Get Work Items Batch", description: "Fetch multiple work items by IDs in a single call.",
    params: [
      { name: "ids", type: "number[]", required: true, description: "Array of work item IDs" },
      { name: "fields", type: "string[]", required: false, description: "Specific fields to return" },
    ],
    returns: "WorkItem[] — array of work items",
    example: "await ado.workItems.getBatch([101, 102, 103])", tags: ["work item", "batch", "multiple", "bulk", "fetch"], readOnly: true,
  },
  {
    id: "work-items.create", domain: Domain.WorkItems, name: "create",
    title: "Create Work Item", description: "Create a new work item (PBI, Task, Bug, Feature, or Epic).",
    params: [
      { name: "project", type: "string", required: true, description: "Project name" },
      { name: "type", type: "string", required: true, description: "Work item type: Product Backlog Item, Task, Bug, Feature, Epic" },
      { name: "fields", type: "object", required: true, description: "Field values as {fieldPath: value}" },
    ],
    returns: "WorkItem — the newly created work item",
    example: 'await ado.workItems.create({ project: "MyProj", type: "Task", fields: { "System.Title": "New task" } })',
    tags: ["work item", "create", "new", "add", "pbi", "task", "bug", "feature", "epic"], readOnly: false,
  },
  {
    id: "work-items.update", domain: Domain.WorkItems, name: "update",
    title: "Update Work Item", description: "Update fields on an existing work item using JSON Patch operations.",
    params: [
      { name: "id", type: "number", required: true, description: "Work item ID" },
      { name: "patches", type: "object", required: true, description: "Array of {path, value} patches, e.g. [{path: '/fields/System.State', value: 'Done'}]" },
    ],
    returns: "WorkItem — the updated work item",
    example: 'await ado.workItems.update(12345, [{ path: "/fields/System.State", value: "Done" }])',
    tags: ["work item", "update", "edit", "modify", "state", "change", "patch"], readOnly: false,
  },
  {
    id: "work-items.delete", domain: Domain.WorkItems, name: "delete",
    title: "Delete Work Item", description: "Delete a work item (moves to recycle bin).",
    params: [{ name: "id", type: "number", required: true, description: "Work item ID" }],
    returns: "void", example: "await ado.workItems.delete(12345)",
    tags: ["work item", "delete", "remove"], readOnly: false,
  },
  {
    id: "work-items.query", domain: Domain.WorkItems, name: "query",
    title: "Query Work Items (WIQL)", description: "Run a WIQL query to find work items matching criteria.",
    params: [
      { name: "project", type: "string", required: true, description: "Project name" },
      { name: "wiql", type: "string", required: true, description: "WIQL query string" },
    ],
    returns: "WorkItem[] — matching work items with requested fields",
    example: 'await ado.workItems.query({ project: "MyProj", wiql: "SELECT [System.Id], [System.Title] FROM WorkItems WHERE [System.State] = \'Active\'" })',
    tags: ["work item", "query", "wiql", "search", "find", "filter", "where"], readOnly: true,
  },
  {
    id: "work-items.list", domain: Domain.WorkItems, name: "list",
    title: "List Backlog Work Items", description: "List work items from the team backlog.",
    params: [
      { name: "project", type: "string", required: true, description: "Project name" },
      { name: "team", type: "string", required: true, description: "Team name" },
      { name: "type", type: "string", required: false, description: "Filter by work item type" },
      { name: "state", type: "string", required: false, description: "Filter by state" },
    ],
    returns: "WorkItem[] — backlog items",
    example: 'await ado.workItems.list({ project: "MyProj", team: "MyTeam" })',
    tags: ["work item", "list", "backlog", "all", "browse"], readOnly: true,
  },
  {
    id: "work-items.addComment", domain: Domain.WorkItems, name: "addComment",
    title: "Add Comment to Work Item", description: "Add a discussion comment to a work item.",
    params: [
      { name: "id", type: "number", required: true, description: "Work item ID" },
      { name: "text", type: "string", required: true, description: "Comment text (supports HTML)" },
    ],
    returns: "Comment — the created comment",
    example: 'await ado.workItems.addComment(12345, "Fixed in commit abc123")',
    tags: ["work item", "comment", "discussion", "note", "reply"], readOnly: false,
  },
  {
    id: "work-items.link", domain: Domain.WorkItems, name: "link",
    title: "Link Work Items", description: "Create a relationship link between two work items.",
    params: [
      { name: "sourceId", type: "number", required: true, description: "Source work item ID" },
      { name: "targetId", type: "number", required: true, description: "Target work item ID" },
      { name: "linkType", type: "string", required: false, description: "Link type (default: System.LinkTypes.Related)" },
    ],
    returns: "void",
    example: "await ado.workItems.link(123, 456, \"System.LinkTypes.Hierarchy-Forward\")",
    tags: ["work item", "link", "relate", "parent", "child", "dependency"], readOnly: false,
  },
  {
    id: "work-items.getChildren", domain: Domain.WorkItems, name: "getChildren",
    title: "Get Child Work Items", description: "Get all child items of a work item (follows Hierarchy-Forward links).",
    params: [{ name: "id", type: "number", required: true, description: "Parent work item ID" }],
    returns: "WorkItem[] — child work items",
    example: "await ado.workItems.getChildren(12345)",
    tags: ["work item", "children", "child", "hierarchy", "parent", "sub-items", "breakdown"], readOnly: true,
  },
  {
    id: "work-items.getRevisions", domain: Domain.WorkItems, name: "getRevisions",
    title: "Get Work Item Revisions", description: "Get the revision history of a work item.",
    params: [{ name: "id", type: "number", required: true, description: "Work item ID" }],
    returns: "WorkItemRevision[] — list of revisions",
    example: "await ado.workItems.getRevisions(12345)",
    tags: ["work item", "revision", "history", "changes", "audit"], readOnly: true,
  },
  {
    id: "work-items.getUpdates", domain: Domain.WorkItems, name: "getUpdates",
    title: "Get Work Item Updates", description: "Get the update history showing field changes.",
    params: [{ name: "id", type: "number", required: true, description: "Work item ID" }],
    returns: "WorkItemUpdate[] — list of updates with old/new values",
    example: "await ado.workItems.getUpdates(12345)",
    tags: ["work item", "updates", "field changes", "history", "diff"], readOnly: true,
  },
  {
    id: "work-items.myWorkItems", domain: Domain.WorkItems, name: "myWorkItems",
    title: "My Work Items", description: "Get work items assigned to the current user.",
    params: [
      { name: "project", type: "string", required: false, description: "Project name (optional filter)" },
    ],
    returns: "WorkItem[] — items assigned to current user",
    example: "await ado.workItems.myWorkItems()",
    tags: ["work item", "my", "mine", "assigned", "me", "current user"], readOnly: true,
  },
  {
    id: "work-items.getComments", domain: Domain.WorkItems, name: "getComments",
    title: "Get Work Item Comments", description: "Get all discussion comments on a work item.",
    params: [{ name: "id", type: "number", required: true, description: "Work item ID" }],
    returns: "Comment[] — list of comments",
    example: "await ado.workItems.getComments(12345)",
    tags: ["work item", "comments", "discussion", "read"], readOnly: true,
  },
  {
    id: "work-items.removeLink", domain: Domain.WorkItems, name: "removeLink",
    title: "Remove Work Item Link", description: "Remove a relationship link from a work item.",
    params: [
      { name: "id", type: "number", required: true, description: "Work item ID" },
      { name: "relationIndex", type: "number", required: true, description: "Index of the relation to remove" },
    ],
    returns: "void", example: "await ado.workItems.removeLink(12345, 0)",
    tags: ["work item", "unlink", "remove link", "detach"], readOnly: false,
  },
  {
    id: "work-items.recycle", domain: Domain.WorkItems, name: "recycle",
    title: "Recycle Work Item", description: "Move a work item to the recycle bin.",
    params: [{ name: "id", type: "number", required: true, description: "Work item ID" }],
    returns: "void", example: "await ado.workItems.recycle(12345)",
    tags: ["work item", "recycle", "soft delete", "trash"], readOnly: false,
  },
  {
    id: "work-items.restore", domain: Domain.WorkItems, name: "restore",
    title: "Restore Work Item", description: "Restore a work item from the recycle bin.",
    params: [{ name: "id", type: "number", required: true, description: "Work item ID" }],
    returns: "WorkItem — the restored work item", example: "await ado.workItems.restore(12345)",
    tags: ["work item", "restore", "undelete", "recover"], readOnly: false,
  },
  {
    id: "work-items.getTypes", domain: Domain.WorkItems, name: "getTypes",
    title: "Get Work Item Types", description: "List available work item types for a project.",
    params: [{ name: "project", type: "string", required: true, description: "Project name" }],
    returns: "WorkItemType[] — available types with names and descriptions",
    example: 'await ado.workItems.getTypes("MyProj")',
    tags: ["work item", "types", "categories", "pbi", "task", "bug", "feature", "epic", "schema"], readOnly: true,
  },
  {
    id: "work-items.getStates", domain: Domain.WorkItems, name: "getStates",
    title: "Get Work Item States", description: "List valid states for a work item type in a project.",
    params: [
      { name: "project", type: "string", required: true, description: "Project name" },
      { name: "type", type: "string", required: true, description: "Work item type" },
    ],
    returns: "WorkItemState[] — valid states with names and categories",
    example: 'await ado.workItems.getStates("MyProj", "Product Backlog Item")',
    tags: ["work item", "states", "workflow", "status", "transitions", "new", "active", "done"], readOnly: true,
  },
];
